### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by DooRooSA** [jifalops/geomag#4]
May we please get a new release with updated dependencies, as this package is now 19 months old. We rely quite heavily on this package.

**Comment by ivanzhadnov** [comment]
Because geomag 0.2.1 depends on intl ^0.17.0 and no versions of geomag match >0.2.1 <0.3.0, geomag ^0.2.1 requires intl ^0.17.0.
So, because ____ depends on both geomag ^0.2.1 and intl ^0.18.0, version solving failed.

it's problem for now(

**Comment by AntoniPochopien** [comment]
Hi, I forked this repository and upgraded the version. You can make use of it as follows:
in your pubspec.yaml file add:

```
  geomag:
    git:
      url: https://github.com/AntoniPochopien/geomag_fork_flutter.git
      ref: master
```

I have deleted example files, so if you need that you can look on previous version. Usage is the same as before
